import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "./providers";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`relative`}>
          <div className="absolute top-0 left-0 right-0 mx-auto w-full h-full radial-gradient-1 -z-10"></div>
          <Header />
          <Providers>{children}</Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
